name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  image_picker: ^1.0.7
  flutter_native_splash: ^2.4.4
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  hexagon: ^0.2.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/full_heart.svg
    - assets/images/half_heart.svg
    - assets/images/broken_heart.svg
    - assets/images/modules/1_basics/ch1/course1/
    - assets/images/achievements.png
    - assets/images/default.png
    - assets/json/courses_pages.json
    - assets/json/success.json
    - assets/json/offline_modules.json
    - assets/json/evaluations_pages.json
