name: Mirroring to Epitech Repository

on: [push, pull_request]

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:EvolOsEIP/mobileApp.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:EvolOsEIP/EvolOsProject.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
