name: Generate Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.5.4'
        channel: 'stable'

    - name: Install dependencies
      run: cd mobile_app && flutter pub get

    - name: Generate Documentation
      run: dart doc

