name: Generate Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        # flutter-version-file: ./mobile_app/pubspec.yaml # path to pubspec.yaml

    - run: flutter --version

    - name: Install dependencies
      run: cd mobile_app && flutter pub get

    - name: Generate Documentation
      run: cd mobile_app ; dart doc

    - name: Pushes documentation to EIP Documentation repository
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source_file: 'mobile_app/doc/api/'
        destination_repo: 'git@github.com:EvolOsEIP/Documentation.git'
        destination_folder: 'MobileApp'
        user_email: 'sebastien.nourry@epitech.eu'
        user_name: 'nourrysebastieN'
        commit_message: 'Update documentation for mobile app'