name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.22.2"

      runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - run: flutter --version

    - name: Install dependencies
      run: cd mobile_app && flutter pub get

    - name: Generate Documentation
      run: cd mobile_app ; dart doc

    - name: Setup Pages
      if: github.ref == 'refs/heads/dev'
      uses: actions/configure-pages@v5

    - name: Upload Artifact
      if: github.ref == 'refs/heads/dev'
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./mobile_app/doc/api"
  deploy-page:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build_and_deploy
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

