name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.22.2"

      runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Enable Flutter Web
      run: cd mobile_app && flutter config --enable-web

    - name: Install dependencies
      run: cd mobile_app && flutter pub get

    - name: Build Flutter Web
      run: cd  mobile_app  && touch .env && flutter build web --release

    - name: Remove href from index.html
      run: sed -i '/<base href="\/">/d' mobile_app/build/web/index.html

    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v5

    - name: Upload Artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./mobile_app/build/web"
  deploy-page:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build_and_deploy
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
